### ISSUE TITLE
Alien can never be eaten by rocket

### ISSUE THREAD

**Issue by shra1dhar** [massoprod/react-mini-rocket-game#1]
So I suppose that you've employed a promixity alert fot the alien. I would like to propose an alerternate scenario where alien changes its psition based on time and rocket can eat up alien if theor coordinates sync. Also, the coordinates of alien can be changed with some time.

I would like to send a PR addressing this issue.

**Comment by patrikmasiar** [comment]
@shra1dhar Hey! Good point!
I am glad, that you checked my application. I was thinking about improving this game time by time also with the idea similar to yours. 

So if you will do a PR, I'll check it!

Thanks!
